slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # General
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_footprint"
    scan_topic: "scan"

    mode: "mapping"

    resolution: 0.05
    map_update_interval: 2.0
    max_laser_range: 10.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1

    transform_publish_period: 0.05
    use_scan_matching: true
    enable_interactive_mode: false
